# Dockerfile
FROM node:18-alpine

WORKDIR /app

# Copiar solo package.json y lock primero para cachear dependencias
COPY app/package*.json ./
RUN npm install

# Copiar el resto del código
COPY app .

# Exponer puerto de desarrollo
EXPOSE 3000

# Comando para iniciar en modo desarrollo
CMD ["npm", "run", "dev"]
